### ISSUE TITLE
代码运行反馈

### ISSUE THREAD

**Issue by liguiqi** [greyovo/markdocx#2]
您好，这是一个非常好的项目，对您的markdocx项目非常感兴趣，但当前我使用不起来，还请调试好下您已发布的代码，请确认它至少可以在他人的电脑上稳定运行。

1、我的环境：VSC+py3.12+使用虚拟环境搭建好了你所说的requirements文件的库
2、用你的build.bat文件打包成EXE后，命令符按照您的要求输入了该项目的readme.md在我电脑中的项目路径，运行无果
3、自己用pyinstaller打包EXE单位件，在终端运行您给的命令提示符，还是无果
4、自己尝试在上述环境中debug你的源代码，运行程序中存在大量的src模块调用的错误，我全部改正后，运行markdocx文件只能运行到-h帮助信息等节点处，没有报错信息，虽然我很想尝试用逐步发去详细了解您的代码，带已经大半天过去了，你的代码我读起来比较生疏，但我觉得您的这个项目当前软件的使用体验是很差的，望改进

或者是我使用姿势不对，如果您有详细的说明文档，还请及时给予反馈，非常感谢

**Comment by greyovo** [comment]
显示出帮助信息说明已经成功运行了，要对md文件转化的话，在运行命令后面加上文件路径的参数即可

**Comment by liguiqi** [comment]
已解决，路径有1-开头，重新换了路径可以运行，非常感谢

**Comment by greyovo** [comment]
> 已解决，路径有1-开头，重新换了路径可以运行，非常感谢

这里说的路径 `1-` 开头是什么意思呢？是目录或者文件包含 `1-` 吗？我刚刚测试了下没问题

**Comment by liguiqi** [comment]
抱歉，也许是我的电脑环境的问题，这个问题应该是个例，也许仅仅发生在我的电脑上，我关闭了打开的其他VSC项目以及相关程序，一开始是有这个问题，重启并更换下载代码后没有这个问题，应该是我一开始的环境没有配好并且后期以debug的心态修改代码造成转换失败。

另外，当前版本的好像不能转换较复杂的MD文件，我转换一份具有很多表格并有重复格式的md文件，能够完成HTML的转换，但在htmltodocx时报错。
```text
(markdocx-master) PS D:\Python_study\test-markdocx\markdocx-master\dist> .\markdocx "D:\Python_study\Myself_working\03-Coding知识积累\00-VS Code学习\VS Code键盘快捷（Windows）.md" 
[IMAGE] fetching: https://img-blog.csdnimg.cn/20190122223515857.png
Traceback (most recent call last):
  File "src\markdocx.py", line 56, in <module>
  File "src\provider\docx_processor.py", line 323, in html2docx
  File "src\provider\docx_processor.py", line 167, in add_table
  File "docx\table.py", line 270, in text
  File "docx\oxml\text\run.py", line 104, in text
  File "docx\oxml\text\run.py", line 134, in append_to_run_from_text
  File "docx\oxml\text\run.py", line 141, in add_text
TypeError: 'NoneType' object is not iterable
[8180] Failed to execute script 'markdocx' due to unhandled exception!
(markdocx-master) PS D:\Python_study\test-markdocx\markdocx-master\dist>

```
